name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache libssl-dev git zip unzip default-jdk python3-pip python3-dev

      - name: Install Buildozer & Cython
        run: |
          python -m pip install --upgrade pip setuptools wheel virtualenv
          pip install buildozer==1.4.0 cython==0.29.33

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/your_app_name-0.1-debug.apk
          asset_name: dam-app.apk
          asset_content_type: application/vnd.android.package-archive
